export const supportedLanguages = {
    en: {
      name: "English",
      translation: "English",
      date: "Date",
      time: "Time",
      today: "Today",
      weekly: "Weekly",
      hourlyForecast: "Hourly Forecast",
      highlights: "Today's Highlights",
      detailedDayWeather: "Detailed Day Weather",
      uvIndex: "UV Index",
      wind: "Wind",
      sunrise: "Sunrise",
      sunset: "Sunset",
      humidity: "Humidity",
      visibility: "Visibility",
      weeklyForecast: "Weekly Forecast",
      minTemp: "Min Temp",
      maxTemp: "Max Temp",
      weatherStatus: "Weather Status",
      city: "City",
      todaysDetails: "Today's Details",
      search: "Search",
      temperature: "Temperature",
      rain: "Rain",
      searchForACity: "Search for a city",
      searchHere: "Search here",
    },
  
  ar: {
    name: "العربية",
    translation: "Arabic",
    date: "التاريخ",
    time: "الوقت",
    today: "اليوم",
    weekly: "أسبوعياً",
    hourlyForecast: "التنبؤ الساعي",
    highlights: "أبرز ملامح اليوم",
    detailedDayWeather: "حالة الطقس التفصيلية لليوم",
    uvIndex: "مؤشر الأشعة فوق البنفسجية",
    wind: "الرياح",
    sunrise: "شروق الشمس",
    sunset: "غروب الشمس",
    humidity: "الرطوبة",
    visibility: "الرؤية",
    weeklyForecast: "التنبؤ الأسبوعي",
    minTemp: "أدنى درجة حرارة",
    maxTemp: "أقصى درجة حرارة",
    weatherStatus: "حالة الطقس",
    city: "المدينة",
    todaysDetails: "تفاصيل اليوم",
    search: "بحث",
    temperature: "درجة الحرارة",
    rain: "المطر",
    searchForACity: "ابحث عن مدينة",
    searchHere: "ابحث هنا",
  },
  fi: {
    name: "Suomi",
    translation: "Finnish",
    date: "Päivämäärä",
    time: "Aika",
    today: "Tänään",
    weekly: "Viikottain",
    hourlyForecast: "Tunnin Ennuste",
    highlights: "Päivän Kohokohdat",
    detailedDayWeather: "Yksityiskohtainen Päivän Sää",
    uvIndex: "UV-indeksi",
    wind: "Tuuli",
    sunrise: "Auringonnousu",
    sunset: "Auringonlasku",
    humidity: "Ilmankosteus",
    visibility: "Näkyvyys",
    weeklyForecast: "Viikoittainen Ennuste",
    minTemp: "Vähimmäislämpötila",
    maxTemp: "Enimmäislämpötila",
    weatherStatus: "Säätila",
    city: "Kaupunki",
    todaysDetails: "Tämän päivän tiedot",
    search: "Haku",
  },
  fi: {
    name: "Suomi",
    translation: "Finnish",
    date: "Päivämäärä",
    time: "Aika",
    today: "Tänään",
    weekly: "Viikottain",
    hourlyForecast: "Tunnin Ennuste",
    highlights: "Päivän Kohokohdat",
    detailedDayWeather: "Yksityiskohtainen Päivän Sää",
    uvIndex: "UV-indeksi",
    wind: "Tuuli",
    sunrise: "Auringonnousu",
    sunset: "Auringonlasku",
    humidity: "Ilmankosteus",
    visibility: "Näkyvyys",
    weeklyForecast: "Viikoittainen Ennuste",
    minTemp: "Vähimmäislämpötila",
    maxTemp: "Enimmäislämpötila",
    weatherStatus: "Säätila",
    city: "Kaupunki",
    todaysDetails: "Tämän päivän tiedot",
    search: "Haku",
    temperature: "Lämpötila",
    rain: "Sade",
    searchForACity: "Etsi kaupunki",
    searchHere: "Etsi täältä"
},
hi: {
  name: "हिन्दी",
  translation: "Hindi",
  date: "तारीख",
  time: "समय",
  today: "आज",
  weekly: "साप्ताहिक",
  hourlyForecast: "प्रति घंटे का पूर्वानुमान",
  highlights: "आज के मुख्य बिंदु",
  detailedDayWeather: "विस्तृत दिन का मौसम",
  uvIndex: "यूवी सूचकांक",
  wind: "हवा",
  sunrise: "सूर्योदय",
  sunset: "सूर्यास्त",
  humidity: "नमी",
  visibility: "दृश्यता",
  weeklyForecast: "साप्ताहिक पूर्वानुमान",
  minTemp: "न्यूनतम तापमान",
  maxTemp: "अधिकतम तापमान",
  weatherStatus: "मौसम की स्थिति",
  city: "शहर",
  todaysDetails: "आज का विवरण",
  search: "खोज",
  temperature: "तापमान",
  rain: "बारिश",
  searchForACity: "शहर की खोज करें",
  searchHere: "यहाँ खोजें"
},

  it: {
    name: "Italiano",
    translation: "Italian",
    date: "Data",
    time: "Ora",
    today: "Oggi",
    weekly: "Settimanale",
    hourlyForecast: "Previsioni Orarie",
    highlights: "Evidenze del Giorno",
    detailedDayWeather: "Previsioni Dettagliate del Giorno",
    uvIndex: "Indice UV",
    wind: "Vento",
    sunrise: "Alba",
    sunset: "Tramonto",
    humidity: "Umidità",
    visibility: "Visibilità",
    weeklyForecast: "Previsioni Settimanali",
    minTemp: "Temp. Min",
    maxTemp: "Temp. Max",
    weatherStatus: "Condizioni Meteo",
    city: "Città",
    todaysDetails: "Dettagli di Oggi",
    search: "Cerca",
  },
  ja: {
    name: "日本語",
    translation: "Japanese",
    date: "日付",
    time: "時間",
    today: "今日",
    weekly: "週間",
    hourlyForecast: "時間ごとの天気予報",
    highlights: "今日のハイライト",
    detailedDayWeather: "詳細な日の天気",
    uvIndex: "UV指数",
    wind: "風",
    sunrise: "日の出",
    sunset: "日没",
    humidity: "湿度",
    visibility: "視界",
    weeklyForecast: "週間天気予報",
    minTemp: "最低気温",
    maxTemp: "最高気温",
    weatherStatus: "天気状況",
    city: "都市",
    todaysDetails: "今日の詳細",
    search: "検索",
  },
  ko: {
    name: "한국어",
    translation: "Korean",
    date: "날짜",
    time: "시간",
    today: "오늘",
    weekly: "주간",
    hourlyForecast: "시간별 예보",
    highlights: "하이라이트",
    detailedDayWeather: "상세 날씨",
    uvIndex: "자외선 지수",
    wind: "바람",
    sunrise: "일출",
    sunset: "일몰",
    humidity: "습도",
    visibility: "가시성",
    weeklyForecast: "주간 예보",
    minTemp: "최저 기온",
    maxTemp: "최고 기온",
    weatherStatus: "날씨 상태",
    city: "도시",
    todaysDetails: "오늘의 상세정보",
    search: "검색",
  },
  // Add more languages here...
};

export default supportedLanguages;
